from .login_form import LoginForm
from .signup_form import SignUpForm
from .bag_form import BagForm
from .basket_form import BasketForm
from .course_images_form import CourseImageForm
from .course_form import CourseForm
from .disc_form import DiscForm
from .bagged_disc_form import BaggedDiscForm
from .update_user_form import UpdateUserForm
from .make_admin_form import MakeAdminForm
