"""creating discs table

Revision ID: f64667877058
Revises: c381741b9c62
Create Date: 2023-09-14 16:27:17.428167

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'f64667877058'
down_revision = 'c381741b9c62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('manufacturer', sa.String(
                        length=40), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('purchase_link', sa.String(), nullable=True),
                    sa.Column('plastics', sa.Text(), nullable=True),
                    sa.Column('speed', sa.Integer(), nullable=False),
                    sa.Column('glide', sa.Integer(), nullable=False),
                    sa.Column('turn', sa.Float(), nullable=False),
                    sa.Column('fade', sa.Float(), nullable=False),
                    sa.Column('diameter', sa.Float(), nullable=True),
                    sa.Column('height', sa.Float(), nullable=True),
                    sa.Column('rim_depth', sa.Float(), nullable=True),
                    sa.Column('rim_width', sa.Float(), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.Column('approved', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE discs SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discs')
    # ### end Alembic commands ###
