"""remove services from course

Revision ID: c56dfd000a51
Revises: e11339d3607b
Create Date: 2023-10-22 14:57:53.811395

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'c56dfd000a51'
down_revision = 'e11339d3607b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('services')

    if environment == "production":
        op.execute(f"ALTER TABLE courses SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
