"""created teepads, adjusted other tables

Revision ID: 2c43dacaad2e
Revises: 79ef21e28d92
Create Date: 2023-10-02 20:00:32.074598

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '2c43dacaad2e'
down_revision = '79ef21e28d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teepads',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('course_id', sa.Integer(), nullable=False),
                    sa.Column('hole_number', sa.Integer(), nullable=False),
                    sa.Column('lat', sa.Float(), nullable=False),
                    sa.Column('lng', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('teepad_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            "courses_foreign_key_baskets", type_='foreignkey')
        batch_op.create_foreign_key(
            "teepads_foreign_key_baskets", 'teepads', ['teepad_id'], ['id'])
        batch_op.drop_column('course_id')

    if environment == "production":
        op.execute(f"ALTER TABLE teepads SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('course_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])
        batch_op.drop_column('teepad_id')

    op.drop_table('teepads')
    # ### end Alembic commands ###
