"""added hole_number to the basket table

Revision ID: 3b5de160dafd
Revises: 39f4318aa44f
Create Date: 2023-09-16 09:56:08.691434

"""
from alembic import op
import sqlalchemy as sa


import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '3b5de160dafd'
down_revision = '39f4318aa44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('hole_number', sa.Integer()))

    if environment == "production":
        op.execute(f"ALTER TABLE bagged_discs SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.drop_column('hole_number')

    # ### end Alembic commands ###
