"""adjusting users table

Revision ID: c381741b9c62
Revises: ffdc0a98111c
Create Date: 2023-09-14 16:01:14.096250

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'c381741b9c62'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('first_name', sa.String(length=50), nullable=False))
        batch_op.add_column(
            sa.Column('last_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))
        batch_op.add_column(
            sa.Column('pdga_number', sa.INTEGER(), nullable=True))
        batch_op.add_column(
            sa.Column('skill_level', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('throwing_preference',
                            sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(
            "pdga_number_unique_constaint", ['pdga_number'])

        if environment == "production":
            op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(
            'pdga_number_unique_constaint', type_='unique')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('admin')
        batch_op.drop_column('throwing_preference')
        batch_op.drop_column('skill_level')
        batch_op.drop_column('pdga_number')
        batch_op.drop_column('image_url')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
