"""added hole_number not null constaint to hole_number column

Revision ID: 79ef21e28d92
Revises: 3b5de160dafd
Create Date: 2023-09-16 10:06:02.216005

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '79ef21e28d92'
down_revision = '3b5de160dafd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('hole_number',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    if environment == "production":
        op.execute(f"ALTER TABLE bagged_discs SET SCHEMA {SCHEMA};")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('baskets', schema=None) as batch_op:
        batch_op.alter_column('hole_number',
                              existing_type=sa.INTEGER(),
                              nullable=True)

    # ### end Alembic commands ###
