"""creating bagged disc table

Revision ID: 5ad33f596d67
Revises: 55e9fd562b5f
Create Date: 2023-09-14 16:38:59.038555

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '5ad33f596d67'
down_revision = '55e9fd562b5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bagged_disc',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('bag_id', sa.Integer(), nullable=False),
                    sa.Column('disc_id', sa.Integer(), nullable=False),
                    sa.Column('weight', sa.Float(), nullable=True),
                    sa.Column('color', sa.String(length=50), nullable=True),
                    sa.Column('plastic', sa.String(length=50), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['bag_id'], ['bags.id'], ),
                    sa.ForeignKeyConstraint(['disc_id'], ['discs.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bagged_disc')
    # ### end Alembic commands ###
